services:
    sic-qa-frontend:
        build:
            context: ..
            dockerfile: devops/Dockerfile
        container_name: sic-qa-frontend
        restart: unless-stopped
        networks:
            - qa_network

networks:
    qa_network:
        external: true
