export enum BreadcrumbEnum {
  FORM = 'Formulario',
  PROFILE = 'Mi Perfil',
  USERS = 'Usuarios',
  AGREEMENTS = 'Lista de Convenios Registrados',
  AGREEMENT = 'Ficha del Convenio',
  PERIODS = 'Ejecución y Reporte del Convenio',
  PERIODS_CLOSING_ADMINISTRATOR = 'REPORTE AVANCE PROCESO DE CIERRE DEL CONVENIO',
  CLOSING = 'Gestión del cierre del Convenio',
  CLOSED = 'Registro del cierre del Convenio',
  CLOSING_LOG_ADMINISTRATOR = 'GESTIÓN DE CIERRE DEL CONVENIO',
  CLOSING_LOG_SUPERVISOR = 'SEGUIMIENTO AL CIERRE DE CONVENIOS',
  PERIODS_CLOSING_SUPERVISOR = 'SEGUIMIENTO AL AVANCE DE CIERRE DEL CONVENIO',
  PERIODS_CLOSING_MANAGER = 'REPORTE AVANCE SEMESTRAL DE CIERRE DEL CONVENIO',
  PERIODS_SUPERVISOR = 'Seguimiento a la ejecución del convenio',
  PERIODS_CLOSING = 'Seguimiento al cierre del convenio',
  PERIODS_MANAGER = 'EJECUCIÓN DEL CONVENIO',
  ADDITIONAL_DOCUMENTS = 'Registro de avance adicional de ejecución de convenio',
  ADDITIONAL_DOCUMENTS_MANAGER = 'Reporte adicional al convenio',
  AGREEMENTS_REGISTER = 'Registrar Convenio',
  AGREEMENTS_UPDATE = 'Actualizar Convenio',
  AGREEMENTS_LOG = 'Bitácora del convenio',
  TRACKING_LOGS = 'Bitácora del periodo',
  CLOSING_NOTIFICATION = 'Notificación inicio del proceso de cierre del convenio',
  AGREEMENT_TRACKING_CLOSED = 'Registro de ejecución y Gestión de Cierre del Convenio',
  }
