export enum IdButtonActionEnum {
  APPROVED = 'approved',
  REJECTED = 'rejected',
  ENROLLED = 'enrolled',
  REGISTERED = 'registered',
  SENT_REQUEST = 'sent_request',
  UPDATE = 'update',
  DELETE = 'delete',
  DOWNLOADS = 'downloads',
  ENABLE = 'enable',
  DISABLE = 'disable',
  HIDE = 'hide',
  SELECT = 'select',
  PARALLEL_CAPACITY = 'parallel_capacity',
  SHOW_EVENTS = 'show_events',
  OPEN_SCHOOL_PERIOD = 'open_school_period',
  CLOSE_SCHOOL_PERIOD = 'close_school_period',
  FILE_LIST = 'file_list',
  SUBJECT_REQUIREMENTS = 'subject_requirements',
  SUSPEND = 'suspend',
  REACTIVATE = 'reactivate',
  VIEW = 'view'
}

export enum LabelButtonActionEnum {
  ADD = 'Agregar',
  ACTIONS = 'Acciones',
  CREATE = 'Crear',
  CANCEL = 'Cancelar',
  RETURN = 'Regresar',
  SAVE = 'Guardar',
  UPDATE = 'Editar',
  VIEW = 'Visualizar',
  DELETE = 'Eliminar',
  DOWNLOAD = 'Descargar',
  DOWNLOADS = 'Descargas',
  SUSPEND = 'Suspender',
  HIDE = 'Ocultar',
  SELECT = 'Seleccionar',
  ENABLE = 'Habilitar',
  DISABLE = 'Deshabilitar',
  SHOW_EVENTS = 'Mostar Eventos',
  OPEN_SCHOOL_PERIOD = 'Abrir Periodo Lectivo',
  CLOSE_SCHOOL_PERIOD = 'Cerrar Periodo Lectivo',
  FILE_LIST = 'Lista de Archivos',
  SUBJECT_REQUIREMENTS = 'Pre y Co Requisitos',
  SYNC = 'Sincronizar',
  CAREERS = 'Carreras',
  CURRICULUMS = 'Mallas Curriculares',
  SUBJECTS = 'Asignaturas',
  PARALLEL_CAPACITY = 'Capacidad Paralelos',
  REACTIVATE = 'Reactivar',
  COMPONENTS = 'Componentes',
  ACTIVITIES = 'Actividades'
}

export enum IconButtonActionEnum {
  ADD = 'pi pi-plus',
  CREATE = 'pi pi-plus',
  SYNC = 'pi pi-sync',
  UPDATE = 'pi pi-pencil',
  CANCEL = 'pi pi-times',
  RETURN = 'pi pi-arrow-left',
  DOWNLOAD = 'pi pi-download',
  DOWNLOADS = 'pi pi-download',
  SAVE = 'pi pi-save',
  SUSPEND = 'pi pi-ban',
  PARALLEL_CAPACITY = 'pi pi-list',
  DELETE = 'pi pi-trash',
  HIDE = 'pi pi-eye-slash',
  SELECT = 'pi pi-check',
  ENABLE = 'pi pi-eye',
  DISABLE = 'pi pi-eye-slash',
  SHOW_EVENTS = 'Mostar Eventos',
  OPEN_SCHOOL_PERIOD = 'Abrir Periodo Lectivo',
  CLOSE_SCHOOL_PERIOD = 'Cerrar Periodo Lectivo',
  FILE_LIST = 'pi pi-file',
  SUBJECT_REQUIREMENTS = 'Pre y Co Requisitos',
  REACTIVATE = 'Reactivar',
  VIEW = 'pi pi-eye'
}

export enum SeverityButtonActionEnum {
  CREATE = 'success',
  ADD = 'success',
  CANCEL = 'danger',
  RETURN = 'warning',
  SAVE = 'primary',
  SYNC = 'info',
  DELETE = 'danger',
  UPDATE = 'warning',
  DOWNLOAD = 'info',
}

